create or replace view v5_dim_user as (
select usr.sys_id as row_wid,
usr.active,
usr.vip,
usr.u_exec,
usr.sys_updated_on,
usr.sys_updated_by,
usr.sys_created_on,
usr.sys_created_by,
usr.name,
usr.first_name,
usr.last_name,
usr.source,
usr.email,
usr.manager,
mgr.name as mgr_name,
mgr.first_name as mgr_first_name,
mgr.last_name as mgr_last_name,
mgr.email as mgr_email,
mgr.title as mgr_title,
mgr.employee_number as mgr_employee_number,
usr.user_name,
usr.department,
dept.name as dept_name,
dept.u_department_number as dept_number,
usr.city,
usr.employee_number,
usr.street,
usr.title,
usr.cost_center,
usr.last_login_time,
usr.location,
loc.name as loc_name,
loc.full_name as loc_full_name,
loc.country as loc_country,
loc.city as loc_city,
loc.zip as loc_zip,
loc.street as loc_street,
usr.phone,
usr.u_reporting_center
from sn_stg_users usr, sn_stg_users mgr, sn_stg_department dept, sn_stg_location loc
where usr.manager = mgr.sys_id (+)
and usr.department = dept.sys_id (+)
and usr.location = loc.sys_id (+));